version: '3'
services: 
  web_laravel:
    container_name: web_laravel
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    networks:
      - rede_laravel

  nginx_laravel:
    build: ./.docker/nginx
    container_name: nginx_laravel
    restart: always
    ports:
      - "8090:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web_laravel
    networks:
      - rede_laravel

  postgres_laravel:
    image: postgres
    container_name: postgres_laravel
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data 
    networks:
      - rede_laravel
      
  pgadmin_laravel:
    image: dpage/pgadmin4
    container_name: pgadmin_laravel
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin_laravel@pgadmin_laravel.com"
      PGADMIN_DEFAULT_PASSWORD: "#pgadmin_laravel@"
    ports:
      - "8091:80"
    volumes:
      - ./PgAdmin:/var/lib/pgadmin
    depends_on:
      - postgres_laravel
    networks:
      - rede_laravel

volumes: 
  PostgreSQL:
  PgAdmin:

networks: 
  rede_laravel:
    driver: bridge